### ISSUE TITLE
Gateway timeout on Login

### ISSUE THREAD

**Issue by epoch18** [Maestro-Zacht/aa-charlink#25]
AAuth 4.1.0 and AA-Charlink 1.4.0

When I go through it, everything works fine. When anyone else does it, they get a generic looking gateway timeout error when they click the blue Login button on the Character Linking screen. Multiple users, various browsers, incognito windows, cleared cache, etc.

**Comment by Maestro-Zacht** [comment]
This is likely an issue with django-esi, which has been addressed here : https://gitlab.com/allianceauth/django-esi/-/merge_requests/82 and https://gitlab.com/allianceauth/django-esi/-/merge_requests/83
If this is your case, the solution is to install the beta version of django-esi, which is v5.3.0b2 . You can do so by doing `pip install django-esi==5.3.0b2` if you are on a traditional installation or by adding
```
django-esi==5.3.0b2
```
to your requirements.txt file if you are on docker.
Let me know if this fixes your issue.

**Comment by epoch18** [comment]
Seems to have resolved my issue. Thank you!

**Comment by Maestro-Zacht** [comment]
Nice, happy to help :D
