### ISSUE TITLE
Combine/merge scopes instead of just adding them to each other

### ISSUE THREAD

**Issue by ppfeufer** [Maestro-Zacht/aa-charlink#28]
It seems `charlink` does not combine/merge scopes, but instead adds them to each other. This might create a list of scopes that is too large and contains duplicates.

## Exhibit A
Adding Member Audit and Corp Tools
![image](https://github.com/Maestro-Zacht/aa-charlink/assets/2989985/92efa3a2-83d6-4527-94ab-fa598bd63b0c)

Both apps require almost the same scopes and a large list of them. Having both checked results in this error on CCP's SSO login page.
![image](https://github.com/Maestro-Zacht/aa-charlink/assets/2989985/80302764-6189-4a66-8d64-6cd528b35741)

Trying them one after the other works as expected.

So I suspect that `charlink` does not check for duplicate scopes when checking multiple apps on that page/widget.

**Comment by Maestro-Zacht** [comment]
Scopes have always been sent only once from the first release, no duplicate are sent: https://github.com/Maestro-Zacht/aa-charlink/blob/main/charlink/views.py#L87
I just tried in my dev with all the current apps, not only the two mentioned and it worked:
![image](https://github.com/Maestro-Zacht/aa-charlink/assets/61846068/5a3efc81-50ec-4637-b211-025ebf6417fb)
![image](https://github.com/Maestro-Zacht/aa-charlink/assets/61846068/9448ed86-f441-407a-bb74-0970cb48ebfa)

I don't know what could cause that error, maybe checking the headers of the request could give some hints

**Comment by Maestro-Zacht** [comment]
Has this happened again? if not, I'll close the issue
