### ISSUE TITLE
Char link errors

### ISSUE THREAD

**Issue by stockholmyaken** [Maestro-Zacht/aa-charlink#29]
O/ I was told to write to you about an error we are having with the Char Link function.
When trying to do both member audit and character audit it gives our new recruit an error 400 

But when doing just one or the other it works perfectly. 

I’ve attached some screenshots below as well

![IMG_5905](https://github.com/Maestro-Zacht/aa-charlink/assets/175286133/af2acbf4-3150-4525-b3b4-14ac94c7d71c)
![IMG_5904](https://github.com/Maestro-Zacht/aa-charlink/assets/175286133/cb1701db-6c93-4513-acfa-37288cbd26d4)
![image](https://github.com/Maestro-Zacht/aa-charlink/assets/175286133/87558a3f-e13e-4b23-a354-803bff44abfc)

**Comment by Maestro-Zacht** [comment]
I'm closing this in favor of #28 to keep everything in one place
